name = "hedge-web"
compatibility_date = "2026-01-31"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL = "https://api.hedge.finance"
